# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.13

      - name: Install dependencies
        run: |
          poetry install

      - name: Format code with black
        run: |
          black .

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install --editable ".[dev]"

      # - name: Format code with black
      #   run: |
      #     black .
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings.
    #     flake8 . --count --exit-zero --max-complexity=10 --statistics
    # - name: Type check with mypy
    #   run: |
    #     mypy . --cache-dir=/dev/null
    # - name: Test with pytest
    #   run: |
    #     pytest tests --cov ./semantic_search --cov-report=xml --cov-config=./.coveragerc
    # - name: Upload coverage to Codecov
    #   # We don't want to push coverge for every job in the matrix.
    #   # Rather arbitrarily, choose to push on Ubuntu with Python 3.7.
    #   if: matrix.python-version == '3.7' && matrix.os == 'ubuntu-latest'  && (github.event_name == 'push' || github.event_name == 'pull_request')
    #   uses: codecov/codecov-action@v3
    #   with:
    #     file: ./coverage.xml
    #     # Ignore codecov failures as the codecov server is not
    #     # very reliable but we don't want to report a failure
    #     # in the github UI just because the coverage report failed to
    #     # be published.
    #     fail_ci_if_error: false
